### ISSUE TITLE
require silently dropped if name of imported module is contained in the file's path

### ISSUE THREAD

**Issue by JaSpa** [theam/require#20]
The changes made by #11 introduce the following problem:

Consider a file `tests/DFATests.hs`

```haskell
module DFATests where
require DFA
```

this drops the the import of `DFA` because `"DFA"` is *contained* in `"tests/DFATests.hs"`.

---

I stumbled upon this problem before organizing my modules hierarchically, so this isn't a real problem because the module name is to become something like `Data.Automaton.DFA` and it's quite unusual to have a path include that verbatim.

If this issue should get fixed (rather than just documented) I am willing to work on it but would like some guidance, since after looking at the discussions of #10 and #11 I'm not really sure how/why that fix works the way it does.

**Comment by NickSeagull** [comment]
Hey @JaSpa , thanks for reporting this!

Indeed, this shouldn't happen and should be fixed 😄 It is a real problem, because when organizing applications, generally one does so by making a hierarchy 😬 

I'd be happy to guide you on this, if you want, you can create a draft PR and we can talk over there.

As a first step, I'd create a failing test that reproduces this 🙂 

Thank you a lot!

**Comment by JaSpa** [comment]
This was solved by #22.
